name: paprle
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - exiftool=12.76=pl5321ha770c72_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h7f98852_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - perl=5.32.1=2_h7f98852_perl5
  - pip=25.1=pyhc872135_2
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.2
      - altgraph==0.17.4
      - asciitree==0.3.3
      - asttokens==3.0.0
      - catkin-pkg==1.0.0
      - certifi==2025.4.26
      - click==8.2.1
      - colorlog==6.9.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - cyclonedds==0.10.2
      - decorator==5.2.1
      - docutils==0.21.2
      - embreex==2.17.7.post6
      - empy==3.3.4
      - etils==1.12.2
      - executing==2.2.0
      - fasteners==0.19
      - filelock==3.18.0
      - fonttools==4.58.0
      - freetype-py==2.5.1
      - fsspec==2025.5.0
      - getch==1.0
      - glfw==2.9.0
      - idna==3.10
      - imagecodecs==2025.3.30
      - imagecodecs-numcodecs==2025.3.30
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - ipydatawidgets==4.3.5
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.0
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lxml==5.4.0
      - manifold3d==3.1.0
      - mapbox-earcut==1.0.3
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - mujoco==3.1.6
      - mujoco-python-viewer==0.1.4
      - networkx==3.4.2
      - ninja==1.11.1.4
      - numcodecs==0.13.1
      - numpy==1.23.0
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - pandas==2.2.3
      - paprle==0.1.0
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycollada==0.6
      - pyexiftool==0.5.0
      - pyglet==1.5.31
      - pygments==2.19.1
      - pyinstaller==6.14.1
      - pyinstaller-hooks-contrib==2025.5
      - pyopengl==3.1.0
      - pyparsing==3.2.3
      - pyqt5==5.15.11
      - pyqt5-qt==5.15.2
      - pyqt5-qt5==5.15.17
      - pyqtgraph==0.13.7
      - pyrealsense2==2.54.1.5217
      - pyrender==0.1.45
      - pyside6==6.9.1
      - pyside6-addons==6.9.1
      - pyside6-essentials==6.9.1
      - pythreejs==2.4.2
      - pytransform3d==3.14.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - rich==14.0.0
      - rich-click==1.8.9
      - rtree==1.4.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - shapely==2.1.1
      - shiboken6==6.9.1
      - six==1.17.0
      - stack-data==0.6.3
      - svg-path==6.3
      - sympy==1.14.0
      - termcolor==3.1.0
      - torch==2.7.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - traittypes==0.2.1
      - trimesh==4.6.10
      - triton==3.3.0
      - tzdata==2025.2
      - unitree-sdk2py==1.0.1
      - urdfpy==0.0.22
      - vhacdx==0.0.8.post2
      - wcwidth==0.2.13
      - xxhash==3.5.0
      - yourdfpy==0.0.57
      - zarr==2.18.3
      - zipp==3.21.0
prefix: /home/obin/miniconda3/envs/paprle
