type: visionpro
name: visionpro

ip: 10.0.0.37 #10.1.10.204
teleop_dt: 0.02
output_type: delta_eef_pose # 'joint_pos' or 'delta_eef_pose'

limb_names: ['left','right'] # order of hands in the output
motion_scale: 1.0

replay: ''#'sample_data/visionpro/sample_for_humanoid.pkl' # path to the replay file
record: False
save_dir: 'sample_data/visionpro/'