type: sim_puppeteer
name: sim_puppeteer_ai_worker

teleop_dt: 0.02
output_type: joint_pos # 'joint_pos' or 'delta_eef_pose'

# for eef-based mapping
motion_mapping: direct_scaling # 'direct_scaling', 'follower_reprojection', 'leader_reprojection'
motion_scale: 1.0

limb_joint_names:
  left:
    - 'arm_l_joint1'
    - 'arm_l_joint2'
    - 'arm_l_joint3'
    - 'arm_l_joint4'
    - 'arm_l_joint5'
    - 'arm_l_joint6'
    - 'arm_l_joint7'
  right:
    - 'arm_r_joint1'
    - 'arm_r_joint2'
    - 'arm_r_joint3'
    - 'arm_r_joint4'
    - 'arm_r_joint5'
    - 'arm_r_joint6'
    - 'arm_r_joint7'

end_effector_link: #
  left: 'gripper_l_link1'
  right: 'gripper_r_link1'

hand_joint_names:
  left: ['gripper_l_joint1']
  right: ['gripper_r_joint1']

hand_limits: # for gripper range mapping
  left: [[0.0, 1.1]]
  right: [[0.0, 1.1]]


init_qpos: [0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

# leader limb -> follower limb
direct_mapping: [] # default is empty, which means 1:1 mapping

asset_cfg:
  asset_dir: 'models/'
  urdf_path: 'models/leaders/ffw_lg2_leader.urdf'
  xml_path: 'models/leaders/ffw_lg2_leader.urdf'

direct_mapping_available_robots: ['ffw_sg2_follower']

render_base: 'mujoco'
viewer_args:
    trimesh:
      pq: [-0.84400246, -0.74844073,  0.63149086,  0.79797548,  0.49961321, -0.17853849, -0.28591218]