mesh_dir: 'models/' # Default directory for meshes
robot_cfg:
  name: g1
  asset_cfg:
    asset_dir: ${mesh_dir} # Directory for assets
    urdf_path: 'models/humanoids/unitree_g1/g1_29dof.urdf' # Path to the URDF file
    xml_path: 'models/humanoids/unitree_g1/g1_29dof.xml' # If you have xml file, specify the path here or just use urdf file here as well
  ignore_collision_pairs: [] # List of collision pairs to ignore, use * for partial match
  teleop_dt: 0.02
  control_dt: 0.002 # Control loop frequency - 125Hz for PAPRAS
  eef_type: null # Type of end effector: 'hand', 'power_gripper', 'parallel_gripper'
  num_eefs: 2 # number of limbs (end effectors) - 1 for single arm, 2 for dual arm...
  limb_joint_names:
    left_arm:
      - 'left_shoulder_pitch_joint'
      - 'left_shoulder_roll_joint'
      - 'left_shoulder_yaw_joint'
      - 'left_elbow_joint'
      - 'left_wrist_roll_joint'
      - 'left_wrist_pitch_joint'
      - 'left_wrist_yaw_joint'
    right_arm:
      - 'right_shoulder_pitch_joint'
      - 'right_shoulder_roll_joint'
      - 'right_shoulder_yaw_joint'
      - 'right_elbow_joint'
      - 'right_wrist_roll_joint'
      - 'right_wrist_pitch_joint'
      - 'right_wrist_yaw_joint'
      - 'waist_yaw_joint'
      - 'waist_pitch_joint'
      - 'waist_roll_joint'
  hand_joint_names:  # No hand for this robot
    left_leg: []
    right_leg: []
    left_arm: []
    right_arm: []
  max_joint_vel: 20.0 # Maximum joint velocity
  world_link: 'pelvis'
  end_effector_link:
    left_arm: left_end_effector_link
    right_arm: right_end_effector_link
  init_qpos: [0,0,0,0,1.57,0,0,
             0,0,0,0,-1.57,0,0, 0, 0, 0]
  prefer_qpos:
    waist_yaw_joint: 0.0
    waist_pitch_joint: 0.0
    waist_roll_joint: 0.0
    left_shoulder_roll_joint: 0.5
    right_shoulder_roll_joint: -0.5
  viewer_args:
    mujoco:
      azimuth: 172.7000000000001
      distance: 2.6093796441399872
      elevation: -28.550000000000004
      lookat: [-0.21228273,  0.03259374, -0.11615278]
    isaacgym:
      cam_pos: [1.41, -0.36, 0.58]
      cam_target: [0.45, -0.23, 0.31]
ik_cfg: # information for inverse kinematics. Use single limb model for each limb.
  # the number of arms in the urdf file, the name of the robot does not matter, but order matters.
  left_arm:
    # chain of joint names from base to end effector
    joint_names: ['left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint', 'left_elbow_joint', 'left_wrist_roll_joint','left_wrist_pitch_joint', 'left_wrist_yaw_joint']
    ee_link: left_end_effector_link
    dt: 0.05
    asset_dir: ${mesh_dir} # Directory for assets
    urdf_path: 'models/humanoids/unitree_g1/g1_29dof.urdf'
    ik_damping: 0.1
    eps: 1e-3
    base_link: pelvis

  right_arm:
    # chain of joint names from base to end effector
    joint_names: ['right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint',
                  'right_wrist_roll_joint','right_wrist_pitch_joint', 'right_wrist_yaw_joint',
                  'waist_yaw_joint', 'waist_pitch_joint', 'waist_roll_joint']
    ee_link: right_end_effector_link
    dt: 0.05
    asset_dir: ${mesh_dir} # Directory for assets
    urdf_path: 'models/humanoids/unitree_g1/g1_29dof.urdf'
    ik_damping: 0.1
    eps: 1e-3
    base_link: pelvis

ros2_cfg:
  lp_filter_alpha: 0.8
  motion_planning: 'interpolation' # moveit or interpolation
  moveit: null
  state_sub_topic: '/lowstate' # Topic to subscribe for joint states
  state_sub_msg_type: 'LowState' # Message type for joint states
  robots:
    left_arm:
      arm_control_topic: '/arm_sdk'
      arm_control_msg_type: 'LowCmd'
      hand_control_topic: ''
      hand_control_msg_type: ''
      arm_state_sub_topic: ${...state_sub_topic}
      hand_state_sub_topic: ${...state_sub_topic}
      arm_state_sub_msg_type: ${...state_sub_msg_type}
      hand_state_sub_msg_type: ${...state_sub_msg_type}
    right_arm:
      arm_control_topic: '/arm_sdk'
      arm_control_msg_type: 'LowCmd'
      hand_control_topic: ''
      hand_control_msg_type: ''
      arm_state_sub_topic: ${...state_sub_topic}
      hand_state_sub_topic: ${...state_sub_topic}
      arm_state_sub_msg_type: ${...state_sub_msg_type}
      hand_state_sub_msg_type: ${...state_sub_msg_type}
camera_cfg: null